name: "[Staging] functions deploy"
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@main
      - name: Install Dependency
        run: npm install
        working-directory: ./functions
      - name: Firebase Service Account Setting step - 1
        run: echo ‘${{ secrets.FIREBASE_SERVICE_ACCOUNT_STAGING }}’ > $HOME/gcloud.json
      — name: Firebase Service Account Setting step - 2
        run: export GOOGLE_APPLICATION_CREDENTIALS=$HOME/gcloud.json
      - name: Deploy
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT_ID: dooray-slash-command-staging
